server:
  port: 8086
spring:
  application:
    name: bliLiber
  datasource:
    password: pilivesa
    url: jdbc:mysql://localhost:3306/user
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialet: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    show-sql: true
